START TRANSACTION;

DROP TABLE IF EXISTS country, participant, result CASCADE;

CREATE TABLE country (
    country_id serial,
    country_name varchar(50) NOT NULL,
    continent varchar(20) NOT NULL,
    CONSTRAINT PK_country PRIMARY KEY(country_id)
);

CREATE TABLE participant (
    participant_id serial,
    first_name varchar(20) NOT NULL,
    last_name varchar(30) NOT NULL,
    age int NULL,
    gender varchar(6) NULL,
    valid_survey boolean NOT NULL CONSTRAINT DF_valid_survey DEFAULT (TRUE),
    CONSTRAINT PK_participant PRIMARY KEY(participant_id)
);

CREATE TABLE result (
    participant_id int NOT NULL, --foreign key
    country_id int NOT NULL,     --foreign key
    CONSTRAINT FK_result_participant_id FOREIGN KEY(participant_id) REFERENCES participant(participant_id),
    CONSTRAINT FK_result_country_id FOREIGN KEY(country_id) REFERENCES country(country_id)
);

INSERT INTO country (country_name, continent)
VALUES
    ('Afghanistan','Asia'), ('Albania','Europe'),
    ('Algeria','Africa'), ('American Samoa','Oceania'),
    ('Andorra','Europe'), ('Angola','Africa'),
    ('Anguilla','North America'), ('Antigua and Barbuda','North America'),
    ('Argentina','South America'), ('Armenia','Asia'),
    ('Aruba','North America'), ('Australia','Oceania'),
    ('Austria','Europe'), ('Azerbaijan','Asia'),
    ('Bahamas','North America'), ('Bahrain','Asia'),
    ('Bangladesh','Asia'), ('Barbados','North America'),
    ('Belarus','Europe'), ('Belgium','Europe'),
    ('Belize','North America'), ('Benin','Africa'),
    ('Bermuda','North America'), ('Bhutan','Asia'),
    ('Bolivia','South America'), ('Bonaire','North America'),
    ('Bosnia and Herzegovina','Europe'), ('Botswana','Africa'),
    ('Brazil','South America'), ('British Virgin Islands','North America'),
    ('Brunei','Asia'), ('Bulgaria', 'Europe'),
    ('Burkina Faso', 'Africa'), ('Burundi','Africa'),
    ('Cambodia','Asia'), ('Cameroon','Africa'),
    ('Canada','North America'), ('Cape Verde','Africa'),
    ('Cayman Islands','North America'), ('Central African Republic','Africa'),
    ('Chad','Africa'), ('Chile','South America'),
    ('China','Asia'), ('Christmas Island', 'Asia'),
    ('Cocos Islands', 'Asia'), ('Colombia','South America'),
    ('Comoros','Africa'), ('Cook Islands','Oceania'),
    ('Costa Rica','North America'), ('Croatia','Europe'),
    ('Cuba','North America'), ('Curacao','North America'),
    ('Cyprus','Europe'), ('Czech Republic','Europe'),
    ('Democratic Republic of the Congo','Africa'), ('Denmark', 'Europe'),
    ('Djibouti','Africa'), ('Dominica','North America'),
    ('Dominican Republic','North America'), ('East Timor','Asia'),
    ('Ecuador','South America'), ('Egypt', 'Africa'),
    ('El Salvador','North America'), ('Equatorial Guinea','Africa'),
    ('Eritrea','Africa'), ('Estonia','Europe'),
    ('Eswatini', 'Africa'),
    ('Ethiopia','Africa'), ('Falkland Islands', 'South America'),
    ('Faroe Islands','Europe'), ('Fiji','Oceania'),
    ('Finland','Europe'), ('France','Europe'),
    ('French Guiana','South America'), ('French Polynesia','Oceania'),
    ('Gabon','Africa'), ('Gambia','Africa'),
    ('Georgia','Asia'), ('Germany','Europe'),
    ('Ghana','Africa'), ('Gibraltar','Europe'),
    ('Greece','Europe'), ('Greenland','North America'),
    ('Grenada','North America'), ('Guadeloupe','North America'),
    ('Guam','Oceania'), ('Guatemala','North America'),
    ('Guernsey','Europe'), ('Guinea','Africa'),
    ('Guinea-Bissau','Africa'), ('Guyana','South America'),
    ('Haiti','North America'), ('Honduras','North America'),
    ('Hong Kong','Asia'), ('Hungary','Europe'),
    ('Iceland','Europe'), ('India','Asia'),
    ('Indonesia','Asia'), ('Iran','Asia'),
    ('Iraq','Asia'), ('Ireland','Europe'),
    ('Isle of Man','Europe'), ('Israel','Asia'),
    ('Italy','Europe'), ('Ivory Coast','Africa'),
    ('Jamaica','North America'), ('Japan','Asia'),
    ('Jersey','Europe'), ('Jordan','Asia'),
    ('Kazakhstan','Asia'), ('Kenya','Africa'),
    ('Kiribati','Oceania'), ('Kosovo','Europe'),
    ('Kuwait','Asia'), ('Kyrgyzstan','Asia'),
    ('Laos','Asia'), ('Latvia','Europe'),
    ('Lebanon','Asia'), ('Lesotho','Africa'),
    ('Liberia','Africa'), ('Libya','Africa'),
    ('Liechtenstein','Europe'), ('Lithuania','Europe'),
    ('Luxembourg','Europe'), ('Madagascar','Africa'),
    ('Malawi','Africa'), ('Malaysia','Asia'),
    ('Maldives','Asia'), ('Mali','Africa'),
    ('Malta','Europe'), ('Marshall Islands','Oceania'),
    ('Martinique','North America'), ('Mauritania','Africa'),
    ('Mauritius','Africa'), ('Mayotte','Africa'),
    ('Mexico','North America'), ('Micronesia','Oceania'),
    ('Moldova','Europe'), ('Monaco','Europe'),
    ('Mongolia','Asia'), ('Montenegro','Europe'),
    ('Montserrat','North America'), ('Morocco','Africa'),
    ('Mozambique','Africa'), ('Myanmar','Asia'),
    ('Namibia','Africa'), ('Nauru','Oceania'),
    ('Nepal','Asia'), ('Netherlands','Europe'),
    ('New Caledonia','Oceania'), ('New Zealand','Oceania'),
    ('Nicaragua','North America'), ('Niger','Africa'),
    ('Nigeria','Africa'), ('Niue','Oceania'),
    ('Norfolk Island','Oceania'), ('North Korea','Asia'),
    ('North Macedonia','Europe'), ('Northern Mariana Islands','Oceania'),
    ('Norway','Europe'), ('Oman','Asia'), ('Palau','Oceania'),
    ('Palestine','Asia'), ('Panama','North America'),
    ('Papua New Guinea','Oceania'), ('Paraguay','South America'),
    ('Peru','South America'), ('Philippines','Asia'),
    ('Pitcairn Islands','Oceania'), ('Poland','Europe'),
    ('Portugal','Europe'), ('Puerto Rico','North America'),
    ('Qatar','Asia'), ('Republic of the Congo','Africa'),
    ('Romania','Europe'), ('Russia','Europe'),
    ('Rwanda','Africa'), ('Reunion','Africa'),
    ('Saint Helena','Africa'), ('Saint Kitts and Nevis','North America'),
    ('Saint Lucia','North America'), ('Saint Pierre and Miquelon','North America'),
    ('Saint Vincent and the Grenadines','North America'), ('Samoa','Oceania'),
    ('San Marino','Europe'), ('Saudi Arabia','Asia'),
    ('Senegal','Africa'), ('Serbia','Europe'),
    ('Seychelles','Africa'), ('Sierra Leone','Africa'),
    ('Singapore','Asia'), ('Slovakia','Europe'),
    ('Slovenia','Europe'), ('Solomon Islands','Oceania'),
    ('Somalia','Africa'), ('South Africa','Africa'),
    ('South Korea','Asia'), ('South Sudan','Africa'),
    ('Spain','Europe'), ('Sri Lanka','Asia'),
    ('Sudan','Africa'), ('Suriname','South America'),
    ('Sweden','Europe'), ('Switzerland','Europe'),
    ('Syria','Asia'), ('Sao Tome and Principe','Africa'),
    ('Taiwan','Asia'), ('Tajikistan','Asia'),
    ('Tanzania','Africa'), ('Thailand','Asia'),
    ('Togo','Africa'), ('Tonga','Oceania'),
    ('Trinidad and Tobago','North America'), ('Tunisia','Africa'),
    ('Turkey','Asia'), ('Turkmenistan','Asia'),
    ('Turks and Caicos','North America'), ('Tuvalu','Oceania'),
    ('United States Virgin islands','North America'), ('Uganda','Africa'),
    ('Ukraine','Europe'), ('United Arab Emirates','Asia'),
    ('United Kingdom','Europe'), ('United States','North America'),
    ('Uruguay','South America'), ('Uzbekistan','Asia'),
    ('Vanuatu','Oceania'), ('Vatican City','Europe'),
    ('Venezuela','South America'), ('Vietnam','Asia'),
    ('Wallis and Futuna','Oceania'), ('Western Sahara','Africa'),
    ('Yemen','Asia'), ('Zambia','Africa'),
    ('Zimbabwe','Africa');

INSERT INTO participant (first_name, last_name, age, gender, valid_survey)
VALUES ('Cody','Rose',28,'M',true),
       ('Noah','Gimben',14,'M',true),
       ('Colleen','Gimben',56,'F',true),
       ('Tia','Gimben',23,'F',true),
       ('Thomas','Gimben',61,'M',true),
       ('Chelsea','Kromer',14,'F',true),
       ('Jean','Kromer',53,'F',true),
       ('Naomi','Loera',null,'F',true),
       ('Milly','Torres',null,'F',true),
       ('Julia','Roscoe',23,'F',true),
       ('Halli','Kromer',20,'F',true),
       ('Analiha','Sanchez',7,'F',true),
       ('Jake','Gonzalez',26,'M',true),
       ('Gladys','Navarro',54,'F',false),
       ('Karla','Sanchez',null,'F',false),
       ('Erin','Gonzalez',27,'F',true),
       ('Diamaris','Rosario',null,'F',true),
       ('Brandon','Mayiras',null,'M',true),
       ('Kelvin','Jackson',null,'M',true),
       ('Zach','Overs',null,'M',true),
       ('Drew','Zaborowski',null,'M',true),
       ('Kelsey','Strouse',null,'F',true),
       ('Elena','Smith',null,'F',true),
       ('Grant','Pappas',null,'M',true),
       ('Gregory','Visnyai',null,'M',true),
       ('Michael','Visnyai',null,'M',true),
       ('Taylor','Zaborowski',null,'F',true),
       ('Therese','Ciehanoski',null,'F',true),
       ('Tom','Miller',null,'M',true),
       ('Aaron','Hall',null,'M',true),
       ('Myrna','Schmidkons',null,'F',true),
       ('Nick','Flock',null,'M',true),
       ('Sandra','Peloquin',null,'F',true),
       ('Marielys','Torres',null,'F',true),
       ('Yeriel','Sanchez',15,'M',true),
       ('Marjorie','Cintron',null,'F',true),
       ('Anna','Everhart',27,'F',true),
       ('Allison','Loera',16,'F',true),
       ('Wesley','Kromer',24,'M',true),
       ('Valerie','Acevedo',null,'F',true),
       ('Jean','Santiago',18,'M',true),
       ('Allison','Nimtz',28,'F',true),
       ('Sarah','Prusz',27,'F',true),
       ('Jeff','Kromer',null,'M',true),
       ('Joshua','Gimben',27,'M',true),
       ('Abby','Kromer',25,'F',true),
       ('Timon','Nimtz',31,'M',true),
       ('Alexsaisha','Cruz',15,'F',true),
       ('David','Irizarry',15,'M',true),
       ('Alyekci','Marrero',16,'F',true),
       ('Deyaneira','Cruzado',17,'F',true),
       ('Dynasty','Ross',18,'F',true),
       ('Martin','Muniz',15,'M',true),
       ('Jan','Seda',18,'M',true),
       ('John','Zylstra',23,'M',true),
       ('Jasmine','Adair',30,'F',true),
       ('Ashlie','Barranco-Aragon',17,'F',true),
       ('Bran','Shehan',null,'M',true),
       ('Ilmaris','Zayas Pagan',34,'F',true),
       ('Linda','Coss',63,'F',true),
       ('John','Coss',null,'M',true);

COMMIT;

















